




















































































































































100%|██████████| 162/162 [05:03<00:00,  1.87s/it]
Traceback (most recent call last):
  File "D:\research\projects\OpenMedLongTailed\main.py", line 126, in <module>
    main(configs)
  File "D:\research\projects\OpenMedLongTailed\main.py", line 30, in main
    train(dataloaders, model, optimizer, configs)
  File "D:\research\projects\OpenMedLongTailed\main.py", line 59, in train
    log_results(configs, results, epoch)
  File "D:\research\projects\OpenMedLongTailed\utils\log_accuracy.py", line 38, in log_results
    np.save(os.path.join(outputs_dir, 'configs.npy'), configs)
  File "C:\Users\julie\anaconda3\Lib\site-packages\numpy\lib\npyio.py", line 545, in save
    arr = np.asanyarray(arr)
          ^^^^^^^^^^^^^^^^^^
ValueError: invalid __array_struct__
{'epoch': 0, 'status': 'train', 'loss': 1.6273924870255552, 'accuracy': [0.406957928802589, 0.43898573692551507, 0.21064814814814814, 0.14296814296814297, 0.5128205128205128, 0.22119815668202766, 0.7987758224942617, 0.42496171516079634]}